version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: educationplatform-postgres
    environment:
      POSTGRES_DB: education_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

#  app:
#    build: .
#    container_name: educationplatform-app
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/education_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: your_password
#      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
#    ports:
#      - "8080:8080"
#    restart: unless-stopped

volumes:
  postgres_data: {}
